### PR TITLE
Fix issue with inline attachments

### LINKED ISSUE #8: How to use inline attachments?
On cake, we use

```
$email->setAttachments([
    'logo.png' => [
        'file' => WWW_ROOT . Configure::read('App.imageBaseUrl') . 'logo.png',
        'contentId' => 'logo'
    ]
])
```

But on the [mailgun-php](https://github.com/mailgun/mailgun-php/blob/af98ed33071fb9336110e5b93448661355538aff/doc/attachments.md#inline-attachments) is

```
$mg->message()->send('example.com', [
  'from'    => 'bob@example.com', 
  'to'      => 'sally@example.com', 
  'subject' => 'Test inline attachments', 
  'text'    => 'Test',
  'inline' => [
    ['filePath'=>'/tmp/foo.jpg', 'filename'=>'test.jpg']
  ]
]);
```

So, is it possible to send inline attachments with this plugin?

### PR DESCRIPTION
**Pull request by alysson-azevedo**
Fixes the inline attachments from cakephp not being set into the correct property.
See more [here](https://github.com/mailgun/mailgun-php/blob/master/doc/attachments.md#inline-attachments).

This fixes #8.

### CODE REVIEW

**Comment by alysson-azevedo** [comment]
@narendravaghela do you think there's a way to test this?

**Comment by narendravaghela** [comment]
@alysson-azevedo You can check out the tests for this plugin and write some assertion code to check this new feature.

**Comment by narendravaghela** [comment]
See this file - https://github.com/narendravaghela/cakephp-mailgun/blob/master/tests/TestCase/Mailer/Transport/MailgunTransportTest.php

**Comment by alysson-azevedo** [comment]
Well, this isn't a new feature. This pull-request fixes a bug in the current behavior.
And the current tests doesn't really help. The [attachment tests](https://github.com/narendravaghela/cakephp-mailgun/blob/master/tests/TestCase/Mailer/Transport/MailgunTransportTest.php#L133-L149) doesn't do anything other than assert the http_endpoint_url.

In the weekend i'll try to add more tests, but meanwhile could you check if it's everything ok and accept the pull? The inline attachments are not working (#8).

**Comment by narendravaghela** [comment]
It is merged now, need to update unit tests.

**Comment by alysson-azevedo** [comment]
Ok, i'll do that asap.

**Pull request merged**
