### PR TITLE
Deprecated json property replaced with getJson() method on Client class

### PR DESCRIPTION
**Pull request by jkimbrel**

### CODE REVIEW

**Comment by narendravaghela** [comment]
Thanks

**Comment by challgren** [comment]
Can we get a new release/tag for this?

**Comment by narendravaghela** [comment]
@challgren Released new version.

https://github.com/narendravaghela/cakephp-mailgun/releases/tag/v3.0.2

**Comment by challgren** [comment]
Thank you!

On Dec 23, 2018 23:59, "Narendra Vaghela" <notifications@github.com> wrote:

@challgren <https://github.com/challgren> Released new version.

https://github.com/narendravaghela/cakephp-mailgun/releases/tag/v3.0.2

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/narendravaghela/cakephp-mailgun/pull/18#issuecomment-449689971>,
or mute the thread

**Pull request merged**
